# Generated by Django 6.0.3 on 2026-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (рус.)')),
                ('name_la', models.CharField(blank=True, max_length=100, verbose_name='Название (лат.)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка на созвездие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Созвездие',
                'verbose_name_plural': 'созвездия',
                'ordering': ['name_ru'],
            },
        ),
    ]
